### ISSUE TITLE
GitHub Actions cache fails with cache key: blob not found

### ISSUE THREAD

**Issue by jojomatik** [docker/buildx#681] opened 2021-07-20 20:59 UTC
Copying from one stage to another failed in one of my repositories today in a Github Actions workflow after a minor change (https://github.com/jojomatik/blockcluster/commit/cdeb83a457f28692cc162e2453a8fe4a36be4ec8) in a workflow file, which shouldn't affect docker at all: https://github.com/jojomatik/blockcluster/runs/3116972956

```
Dockerfile:62
--------------------
  60 |     RUN cd backend && npm install --only=prod
  61 |     
  62 | >>> COPY --from=builder /usr/games/blockcluster/dist dist
  63 |     COPY --from=builder /usr/games/blockcluster/backend/dist backend/dist
  64 |     COPY --from=builder /usr/games/blockcluster/.env ./
--------------------
error: failed to solve: failed to compute cache key: blob not found
Error: buildx failed with: error: failed to solve: failed to compute cache key: blob not found
```
I'm not sure where exactly this error message comes from and I wasn't able to pin it down with a google search either. So I'm not entirely sure if this is a buildx issue or an issue with one of its dependencies?

This is the relevant section in the workflow file: https://github.com/jojomatik/blockcluster/blob/cdeb83a457f28692cc162e2453a8fe4a36be4ec8/.github/workflows/publish.yml#L92-L111

I've since tried to update it to use the non-rc versions (https://github.com/jojomatik/blockcluster/commit/d4488bae0dcd91ea99e85d6f05f839bf7ff536ec), but it has the same issues. Yesterday those workflows worked like a charm.

If I open up this issue in the wrong repository, I'm sorry. I'm not yet fully comprehending how all these docker parts work together :)

I'd be grateful if you'd find some time to look into this, Thank you! If you need additional information, feel free to ask. I couldn't find a PR template though.

**Comment by jojomatik** [comment] 2021-07-20 22:22
It seems to me like the error is coming from buildkit, at least that is the only place where I can find this snippet: 
https://github.com/moby/buildkit/blob/2a4577efabed1b4404e2884ef56873b8c0a42e95/cache/remotecache/gha/gha.go#L319

```go
        ce, err := p.ci.cache.Load(ctx, key)
	if err != nil {
		return nil, err
	}
	if ce == nil {
		return nil, errors.Errorf("blob not found")
	}
```

Should I open an issue in that repository?

**Comment by tonistiigi** [comment] 2021-07-21 06:12
@crazy-max If you're looking into this, the question is why https://github.com/moby/buildkit/pull/1498/files doesn't work properly in this case and fall back gracefully(assuming blob is legit and there is no other corruption). I guess it might be because `Load` returns a lazy remote reference and actual data is pulled later. In that case, we should verify the blob during load already, and `ReaderAt` only invokes the download.

**Comment by crazy-max** [comment] 2021-07-21 08:48
@tonistiigi

> In that case, we should verify the blob during load already

Agree, I also think it might be a rough case where @jojomatik is using the [`actions/cache` in other jobs in his workflow](https://github.com/jojomatik/blockcluster/blob/cdeb83a457f28692cc162e2453a8fe4a36be4ec8/.github/workflows/publish.yml#L46-L65) that could GC some blobs.

@jojomatik Can you enable debug in your workflow for the `setup-buildx-action` step?

```yaml
- name: Set up Docker Buildx
  uses: docker/setup-buildx-action@v1
  with:
    version: v0.6.0
    buildkitd-flags: --debug
```

**Comment by jojomatik** [comment] 2021-07-21 09:50
> @jojomatik Can you enable debug in your workflow for the setup-buildx-action step?

Yes, here you go: https://github.com/jojomatik/blockcluster/commit/2a26e2a9ccf282af27d46c3275302cb23d3f160e [(workflow)](https://github.com/jojomatik/blockcluster/runs/3122544419).

> I also think it might be a rough case where @jojomatik is using the actions/cache in other jobs in his workflow that could GC some blobs.

I believe I checked the docs at least to see if I'm exceeding some sort of storage quota and think I was well below that, but it's entirely possible that either
- I cache more than I believe and therefore exceed some sort quota, or
- my jobs somehow interfere with each other (but I don't think so, as it worked pretty great in the past).

But I think in either way it shouldn't just fail but rather rebuild that stage, don't you think?

On another note: the last steps (14 - 16) of the `builder` stage shouldn't actually be read from cache as it is rebuilt, if I understand the logic correctly:

```
#34 [builder 14/16] RUN npm run build
#34 0.282 
#34 0.282 > blockcluster-frontend@0.8.0 build
#34 0.282 > vue-cli-service build
#34 0.282 
[...]
#34 42.52 
#34 42.52   Images and other types of assets omitted.
#34 42.52 
#34 42.52  DONE  Build complete. The dist directory is ready to be deployed.
#34 42.52  INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
#34 42.52       
#34 DONE 43.1s
```

---
*Not sure if these might be connected but I remember that I had [one failed workflow](https://github.com/jojomatik/blockcluster/runs/3105621919) in the past. It failed as I had already merged the PR and deleted the branch before the workflows were complete. Maybe that one corrupted the cache somehow?*

**Comment by crazy-max** [comment] 2021-07-21 10:13
@jojomatik 

> Edit: I don't see any difference. Not sure if it worked?

See https://github.com/docker/setup-buildx-action#buildkit-container-logs

> But I think in either way it shouldn't just fail but rather rebuild that stage, don't you think?

Yes errors should be ignore by cache loader. That's an issue that needs to be fixed on BuildKit like @tonistiigi said.

> I cache more than I believe and therefore exceed some sort quota, or

Can you use a fresh `scope` and let me know?:

```yaml
          cache-from: type=gha,scope=blockcluster
          cache-to: type=gha,scope=blockcluster
```

**Comment by jojomatik** [comment] 2021-07-21 11:55
> See https://github.com/docker/setup-buildx-action#buildkit-container-logs

Thanks :)

> Can you use a fresh scope and let me know?

Yes: https://github.com/jojomatik/blockcluster/commit/f180097486fcef83398b0177a95cc5285991dcde [(workflow)](https://github.com/jojomatik/blockcluster/runs/3123494575). That one worked fine, as no cache is available. Should I try to rerun it to see whether the cache is loaded on a second run?

*In case it helps: I just had a look, the other caches for frontend and backend CI seem to be around 160MB (2 * 80MB as I cache `node_modules` and `~/.npm` as a fallback in case the dependencies change). The docker cache was around 800MB before I switched to the new cache backend (https://github.com/jojomatik/blockcluster/runs/3093472329). Not sure where I can find the new size.*

**Comment by crazy-max** [comment] 2021-07-21 13:25
@jojomatik 

> Should I try to rerun it to see whether the cache is loaded on a second run?

Yes please.

**Comment by jojomatik** [comment] 2021-07-21 13:57
Rerun complete: https://github.com/jojomatik/blockcluster/runs/3124430755

Not sure if it's representative though, as it didn't have to decompress (not sure if this is the right term, I hope you know what I mean) the cache, to build further layers. It just realized that every layer was already cached and pushed it to the registry again.

I've gone ahead and added a small change (https://github.com/jojomatik/blockcluster/commit/511a3f1b6d541f50597769020b97ecc435caa67d) that should trigger a [new workflow](https://github.com/jojomatik/blockcluster/runs/3124538746) with a new vue rebuild (builder 14/16) as the commit sha changed. 

Seems like this worked as well. Does this confirm that my cache was somehow corrupted?

**Comment by relu** [comment] 2021-07-28 08:43
I'm also seeing this issue on a multi-stage image build. As you can see below it doesn't necessarily happen when doing cross-stage copying:
```
#16 exporting to oci image format
#16 exporting layers done
#16 exporting manifest sha256:45bdcb7e1f439a4b4b7d1514516b415b8a463f19abf8bd61f96a7532c6d4dbf7 done
#16 exporting config sha256:31819a14401a1cb90b358b07accd8505ce36b196b06a0b0503a58d8b0344f40f done
#16 ERROR: blob not found

#15 [base 9/9] COPY ./bin ./bin
#15 sha256:b15f66665ffaddb1d8fc6128396fd3947d9b89ef182ff28fffa6957986706015 0B / 4.47kB
#15 CACHED
------
 > exporting to oci image format:
------
error: failed to solve: blob not found
Error: buildx failed with: error: failed to solve: blob not found
```

Also probably worth mentioning is that these jobs run on self-hosted runners.

**Comment by crazy-max** [comment] 2021-07-29 18:14
Thanks for your feedback everyone.

> Seems like this worked as well. Does this confirm that my cache was somehow corrupted?

@jojomatik Blobs are somehow missing but it should not failed in this case actually. We are going to investigate on this issue.

**Comment by JanJakes** [comment] 2021-08-09 07:36
Run into probably the same issue – with `type=gha` (Buildx action with `v0.6.0`) and using `scope`. For some time the builds are OK and then suddenly they start to fail with:
```yml
error: failed to solve: failed to compute cache key: blob not found
Error: buildx failed with: error: failed to solve: failed to compute cache key: blob not found
```
It fails on `COPY . .` in the first stage of multi-stage build. There is almost nothing before that:
```Dockerfile
FROM node:14-buster-slim as packages
WORKDIR /build
COPY . .
```
And we use:
```yml
context: .
file: api/Dockerfile
```

**Comment by Niek** [comment] 2021-08-16 08:44
Same issue here, out of nowhere the builds start failing. Disabling the cache is our current workaround.

**Comment by patrikholcak** [comment] 2021-09-02 07:18
Same issue here (private project). We have been using the `gha` cache for about 10 days and started seeing the same issue on all builds across branches, always failing on the step that has changed from build to build. The image with all layers is around 200MB (.NET Core app) with a couple of builds per day. We also cache node_modules for frontend — in a different workflow — same way as @jojomatik does.

We have reverted to using manual [buildx cache](https://evilmartians.com/chronicles/build-images-on-github-actions-with-docker-layer-caching) and it works but isn’t really much of an improvement compared to not caching at all.

```
#30 [frontend  9/10] COPY js ./js
#30 ERROR: blob not found
------
 > [frontend  9/10] COPY js ./js:
------
Dockerfile:21
--------------------
  19 |     COPY css ./css
  20 |     COPY less ./less
  21 | >>> COPY js ./js
  22 |     RUN yarn build
  23 |     
--------------------
error: failed to solve: failed to compute cache key: blob not found
Error: buildx failed with: error: failed to solve: failed to compute cache key: blob not found
```

```yaml
runs-on: ubuntu-20.04
steps:
  - uses: actions/checkout@v2
  - uses: docker/setup-buildx-action@v1
  - uses: docker/login-action@v1
      with:
        registry: ghcr.io
  - uses: docker/build-push-action@v2
     with:
       context: .
       push: true
       tags: ghcr.io/…
       cache-from: type=gha
       cache-to: type=gha,mode=max
```

**Comment by crazy-max** [comment] 2021-10-05 09:02
Should be fixed since [BuildKit 0.9.1](https://github.com/moby/buildkit/releases/tag/v0.9.1).

**Comment by fforootd** [comment] 2021-10-05 09:07
Thanks for the info and the good work! 🎉

**Comment by crazy-max** [comment] 2021-10-05 09:17
If you encounter this kind of issue with GHA cache again please open an issue on BuildKit repo as this is mostly a backend issue. Thanks.

**Closed by crazy-max** 2021-10-05 09:17 UTC
Labels: needs-investigation, buildkit, area/github-actions

**Comment by Niek** [comment] 2021-10-05 10:22
> Should be fixed since [BuildKit 0.9.1](https://github.com/moby/buildkit/releases/tag/v0.9.1).

Do we need to specify this in the `docker/setup-buildx-action` step until a new version is released?
```yaml
with:
  driver-opts: image=moby/buildkit:0.9.1
```

**Comment by crazy-max** [comment] 2021-10-05 10:45
@Niek 

> Do we need to specify this in the docker/setup-buildx-action step until a new version is released?

Not needed the default tag has been updated.

**Comment by KevinMind** [comment] 2024-03-15 10:18
Ran into this today with v0.13.0 buildkit

https://github.com/mozilla/test-github-features/actions/runs/8294601823/job/22699933199?pr=20

**Comment by tonistiigi** [comment] 2024-03-18 05:07
@KevinMind and others reacting: This is a closed issue, please don't use it to report a regression in a new release. If it is same as https://github.com/moby/buildkit/issues/4765 you can post your full issue details in there. There is a candidate fix in https://github.com/moby/buildkit/pull/4771 for testing.
