### ISSUE TITLE
Need to do base image verification while doing the docker build

### ISSUE THREAD

**Issue by manojgollaprolu21** [docker/buildx#1895] opened 2023-06-19 09:45 UTC
### Description

While doing a docker build using the docker file need to verify the DCT signing of the base image in the docker file, this option was present in the older docker engine using the below flag 
`docker build --disable-content-trust=False . -t <reponame>`

In the latest docker engine 23.0.3 how do we verify the base image??

Thank you

**Comment by crazy-max** [comment] 2023-07-17 09:08
duplicate of https://github.com/docker/buildx/issues/987#issuecomment-1059260669

You can use the legacy builder in the meantime:

```
DOCKER_BUILDKIT=0 docker build ...
```

**Closed by crazy-max** 2023-07-17 09:08 UTC
Labels: kind/enhancement, area/feature-parity, status/triage
