### ISSUE TITLE
PATH env variable gets overwritten when building Windows images

### ISSUE THREAD

**Issue by claudiubelu** [docker/buildx#375] opened 2020-08-31 17:41 UTC
When building Windows images with ``docker buildx``, the image's ``PATH`` env variable gets overwritten with a Linux ``PATH`` env variable.

Sample ``Dockerfile``:

ARG BASEIMAGE
FROM $BASEIMAGE

ENTRYPOINT ["cmd.exe", "/s", "/c"]

Command: ``docker buildx build --no-cache --pull --output=type=registry --platform windows/amd64 --build-arg BASEIMAGE=mcr.microsoft.com/windows/nanoserver:1809 -t claudiubelu/path-sample:1.0  .``

We can check the ``PATH`` env variable:

    docker run claudiubelu/path-sample:1.0 echo %PATH%
    /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

The env variable can be overwritten in the ``Dockerfile``, resulting in an appropriate Windows ``PATH`` env variable:

    ARG BASEIMAGE
    FROM $BASEIMAGE

    # NOTE(claudiub): docker buildx sets the PATH env variable to a Linux-like PATH, which is not desirable.
    ENV PATH="C:\bin;C:\Windows\System32;C:\Windows;"

    ENTRYPOINT ["cmd.exe", "/s", "/c"]

docker buildx version: github.com/docker/buildx v0.4.1-25-ge24e04b e24e04be572034efbcc9e20fcf720d6b10646487

**Comment by tonistiigi** [comment] 2020-08-31 18:49
duplicate of https://github.com/moby/buildkit/issues/1560

**Closed by tonistiigi** 2020-08-31 18:49 UTC
