### ISSUE TITLE
 Error: cannot copy to non-directory with buildx only

### ISSUE THREAD

**Issue by joshuaavalon** [docker/buildx#150] opened 2019-09-25 05:37 UTC
I use the following Dockerfile:

```Dockerfile
FROM alpine

COPY /root/ /
```

where `/root/` contains a single file in `root/var/spool/cron/crontabs/root`.

If I run `docker build .`,  it builds successfully. However, if I use `docker buildx build .`

> failed to solve with frontend dockerfile.v0: failed to build LLB: cannot copy to non-directory: /tmp/buildkit-mount656587830/var/spool/cron/crontabs

**Comment by FernandoMiguel** [comment] 2019-09-25 05:41
@joshuaavalon is that a symbolic link?

**Comment by joshuaavalon** [comment] 2019-09-25 05:45
@FernandoMiguel No. Actually, you can see [here](https://github.com/joshuaavalon/test-github-action).

The build log is [here](https://github.com/joshuaavalon/test-github-action/commit/87cf8d55537e301f0b6c5a98ebe444d3c8c2db58/checks)

**Comment by joshuaavalon** [comment] 2019-09-25 05:47
Also, I have tried if `/root/` only has `/root/a.json`, it builds fine. May be it has something to do with nested directories.

**Comment by FernandoMiguel** [comment] 2019-09-25 05:54
Ah! Someone already made an action to get buildx. Ahahaha
I should have done the same.... I building from source

**Comment by FernandoMiguel** [comment] 2019-09-25 05:55
I'm going to be offline all day so can't test this.
But I'll try to reproduce the nested use case

**Comment by tonistiigi** [comment] 2019-09-25 18:20
This is actually the same error I get when I try the same command with regular `cp`. "cp: target '/var/spool/./cron/crontabs' is not a directory" . It's a bit weird case as `cron/crontabs` is a symlink to a directory (not a file what you might expect from this error). I think it is fair to consider the old behavior as a bug as it may have very unexpected results. I verified that the behavior is consistent with fileop and dockerfile-copy implementations.

The issue appears because in alpine base image, `/var/spool/cron/crontabs` is a symlink to `/etc/crontabs`, but in your context you have a directory with matching path. So the correct way to write this instruction would be:

```
COPY /root/var/spool/cron/crontabs /var/spool/cron/crontabs
```
or
```
COPY /root/var/spool/cron/crontabs /etc/crontabs
```
or just rename the file to `/etc/crontabs/root` under your context if you want to copy full root.

@tiborvass

**Comment by FernandoMiguel** [comment] 2019-09-25 18:29
I expected as much from overriding a symlink. didnt had the time to test it.
file-ops over symlinks are confusing and tend to fail

**Comment by tiborvass** [comment] 2019-09-25 21:40
Ok, so the rationale for the cp command's design is that the user shall be guaranteed that the copy operation puts files exclusively under the destination directory. Symlinks can point outside of the destination which would break that guarantee. So I'm fine with qualifying the legacy builder's behavior as incorrectly lenient.

In this specific case, I would probably go with the 3rd workaround: renaming the crontab to `/etc/crontabs/root` in the context.

I'm closing this as buildkit/buildx behaves as intended. Feel free to continue discussing if need be.

**Closed by tiborvass** 2019-09-25 21:40 UTC
Labels: buildkit

**Comment by FernandoMiguel** [comment] 2019-09-25 21:41
@tiborvass any plan to treat the behaviour of the old Docker build as a bug and fix it?
Might break a few people implementations

**Comment by Nek-** [comment] 2020-04-29 16:49
I have no symlink but have the same issue. The old builder is working as expected, but this does not work:

```Dockerfile
COPY docker/manager-app/manager/etc/. /etc/
```

There is no symlinks. The output is:
```
=> ERROR [builder 4/7] COPY docker/manager-app/manager/etc/ /etc/
------
 > [builder 4/7] COPY docker/manager-app/manager/etc/ /etc/:
------
failed to solve with frontend dockerfile.v0: failed to build LLB: cannot copy to non-directory: /var/lib/docker/aufs/mnt/mzdig9xzkf3pg13mr1grvfnvg/etc/service
```

My folders are organized the following:

```
▾ docker/
  ▾ manager-app/
    ▾ manager/
      ▾ etc/
        ▾ nginx/
            nginx.conf
        ▾ php7/
          ▾ conf.d/
              custom.ini
            php-fpm.conf
        ▾ service/
          ▾ nginx/
              run*
          ▾ php-fpm/
              run*
        Dockerfile
 ```

So everything should be ok... But it's not.

**Comment by tonistiigi** [comment] 2020-04-29 16:55
The non-directory is in the destination, already inside the image. Eg. if it is not a symlink your case is equivalent to 

```
/tmp # mkdir -p src/services/nginx
/tmp # mkdir -p dest
/tmp # echo aa > dest/services
/tmp # cp -a src/. dest/
cp: target 'dest/./services' is not a directory
```

**Comment by Nek-** [comment] 2020-04-29 17:05
Oh, indeed, the `services` file was existing inside the image, that's why it failed. The old builder was overriding this...

At least if somebody has this kind of issue, he can find an answer here now. Thanks :).

**Comment by Stiefmeister** [comment] 2022-05-09 11:41
> Oh, indeed, the `services` file was existing inside the image, that's why it failed. The old builder was overriding this...
> 
> At least if somebody has this kind of issue, he can find an answer here now. Thanks :). (and wow, that quick answer)

Having the same problem, how did you actually solve it? Thanks a lot in advance

**Comment by mitar** [comment] 2023-04-26 19:52
This broke quite a few of my Dockerfiles where I have `etc` directory in my git repository I want to copy over into the image and merge directories/files in there. Now I have to explicitly list all subdirectories in my Dockerfiles.
