### ISSUE TITLE
using docker buildx failed to pull image

### ISSUE THREAD

**Issue by shixinlishixinli** [docker/buildx#2059] opened 2023-09-26 13:19 UTC
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

using docker buildx  failed to pull image. but i can get this image by docker pull .  

```
docker buildx build .      [+] Building 30.1s (2/2) FINISHED                                          docker-container:cool_cray
 => [internal] load build definition from Dockerfile                                             0.0s
 => => transferring dockerfile: 862B                                                             0.0s
 => ERROR [internal] load metadata for gcr.io/distroless/static:latest                          30.0s
------
 > [internal] load metadata for gcr.io/distroless/static:latest:
------
WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load
Dockerfile:16
--------------------
  14 |
  15 |
  16 | >>> FROM gcr.io/distroless/static:latest
  17 |     MAINTAINER Marcin Wielgus "mwielgus@google.com"
  18 |
--------------------
ERROR: failed to solve: gcr.io/distroless/static:latest: failed to do request: Head "https://gcr.io/v2/distroless/static/manifests/latest": dial tcp: lookup gcr.io: i/o timeout
```

```
docker pull  gcr.io/distroless/static:latest
latest: Pulling from distroless/static
Digest: sha256:e7e79fb2947f38ce0fab6061733f7e1959c12b843079042fe13f56ca7b9d178c
Status: Image is up to date for gcr.io/distroless/static:latest
gcr.io/distroless/static:latest
```

```
cat /etc/docker/daemon.json
{
     "features":{"buildkit":false},
     "exec-opts":["native.cgroupdriver=systemd"],
    "registry-mirrors": ["https://registry.docker-cn.com","https://hub-mirror.c.163.com","https://registry.aliyuncs.com","https://docker.mirrors.ustc.edu.cn"],
    "dns": ["172.18.0.1","74.125.204.82","142.250.102.82","10.248.2.5", "10.239.27.236", "172.17.6.9", "10.0.0.2", "8.8.8.8","127.0.0.53"],
         "insecure-registries": [
                 "nunu-pc.bj.intel.com:5000",
                 "nvbox.bj.intel.com:5000"
         ]
}
```

```
docker buildx create --driver-opt env.https_proxy=http://child-prc.intel.com:913 --driver-opt env.http_proxy=http://child-prc.intel.com:913
```

### Expected behaviour

docker buildx build successfully

### Actual behaviour

pull image failed 

### Buildx version

github.com/docker/buildx v0.11.2 9872040

### Builders list

```text
docker buildx ls
NAME/NODE            DRIVER/ENDPOINT             STATUS   BUILDKIT       PLATFORMS
amazing_khorana      docker-container
  amazing_khorana0   unix:///var/run/docker.sock inactive
confident_perlman    docker-container
  confident_perlman0 unix:///var/run/docker.sock stopped
cool_cray            docker-container
  cool_cray0         unix:///var/run/docker.sock running  v0.12.2        linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/386
cranky_banzai        docker-container
  cranky_banzai0     unix:///var/run/docker.sock inactive
eager_tharp          docker-container
  eager_tharp0       unix:///var/run/docker.sock inactive
exciting_mcnulty     docker-container
  exciting_mcnulty0  unix:///var/run/docker.sock stopped
flamboyant_rubin *   docker-container
  flamboyant_rubin0  unix:///var/run/docker.sock running  v0.12.2        linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/386
gracious_edison      docker-container
  gracious_edison0   unix:///var/run/docker.sock inactive
modest_sutherland    docker-container
  modest_sutherland0 unix:///var/run/docker.sock inactive
peaceful_agnesi      docker-container
  peaceful_agnesi0   unix:///var/run/docker.sock inactive
testbuilder          docker-container
  testbuilder0       unix:///var/run/docker.sock running  v0.12.2        linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/386
default              docker
  default            default                     running  v0.8.2+eeb7b65 linux/amd64, linux/386
```

### Configuration

```dockerfile
FROM gcr.io/distroless/static:latest

MAINTAINER Marcin Wielgus "mwielgus@google.com"

ARG ARCH
COPY updater-$ARCH /updater

ENTRYPOINT ["/updater"]
CMD ["--v=4", "--stderrthreshold=info", "--updater-interval=10s"]
```

**Comment by jsternberg** [comment] 2023-09-26 14:42
Does this work when there's no http proxy involved or is the http proxy required to access the image? Also, does the same thing occur with the default builder?

I'm wondering if the http proxy information is being included separately between the docker daemon and buildkit. I can take a look to see. Go's default http client will include detecting a proxy from the environment but a manually constructed http client doesn't perform any proxying by default.

**Comment by shixinlishixinli** [comment] 2023-09-26 15:10
> Does this work when there's no http proxy involved or is the http proxy required to access the image? Also, does the same thing occur with the default builder?
> 
> I'm wondering if the http proxy information is being included separately between the docker daemon and buildkit. I can take a look to see. Go's default http client will include detecting a proxy from the environment but a manually constructed http client doesn't perform any proxying by default.

i must use proxy to pull this image .  the image can not be pulled without proxy in my country.
i can pull this image by docker pull , because i have set proxy in this file ( /etc/docker/daemon.json)
 i try to use  --driver-opt , but it is also not useful.

do you have any suggestions about how to skip the downloading image . or  how to pull image in docker buildx with proxy

Best
Lisa Shi

**Comment by jsternberg** [comment] 2023-09-26 15:26
@shixinlishixinli does the proxy work if you use the `default` builder rather than the custom `docker-container` ones? That will help me narrow down where the problem is happening.

I'm still new to the buildkit backend, but I believe the default builder is embedded within docker and shares the same image store. The `docker-container` driver allows you to run newer or older versions of buildkit or keep buildkit separate from the docker daemon itself, but I believe it uses its own image store so it would pull the images itself. My guess is that the proxy forwarding probably works for the default builder (using the `docker` driver) but the http proxy configuration isn't being forwarded to the `docker-container` driver properly.

@crazy-max thanks. I'll start poking around there to see what I find.

**Comment by crazy-max** [comment] 2023-09-26 15:36
> My guess is that the proxy forwarding probably works for the default builder (using the `docker` driver)

Proxy config from docker client config is set for any type of builder (node): https://github.com/docker/buildx/blob/e018f8b6fbf746e4ac4f019bc3918c92c67b927a/builder/node.go#L68

And passed as a build-arg frontend attr: https://github.com/docker/buildx/blob/e018f8b6fbf746e4ac4f019bc3918c92c67b927a/build/build.go#L619-L623

Then used as llb.ProxyEnv on BuildKit: https://github.com/moby/buildkit/blob/5e6497c943e65a4f914f323e21af12e0e44276bd/frontend/dockerfile/dockerfile2llb/convert.go#L1597-L1626

For ExecOps: https://github.com/moby/buildkit/blob/5e6497c943e65a4f914f323e21af12e0e44276bd/client/llb/state.go#L281

For images you need to set the registry mirror config: https://docs.docker.com/build/buildkit/configure/#registry-mirror

**Comment by crazy-max** [comment] 2023-10-20 12:29
@shixinlishixinli Let us know if https://github.com/docker/buildx/issues/2059#issuecomment-1735793524 solves your issue. Closing in the meantime.

**Closed by crazy-max** 2023-10-20 12:29 UTC
Labels: status/triage
