### ISSUE TITLE
Add to the "docker build --output" the parmate "target" and "filter"

### ISSUE THREAD

**Issue by petit-aigle** [docker/buildx#2627] opened 2024-07-23 16:27 UTC
### Description

Currently, with "docker build --output", for type "local" or "tar" we cannot target (or filter) which folders (or files) inside the build image should be exported as from the output.

It would be interesting to add the concept of a "targets" or an equivalent, allowing us to specify a list of the "PATH" of the directorys (or files) we want to export from the newly built image.

Additionally, it would be beneficial to have the ability to add "filters", enabling us to pass a list of conditions using "Wildcard Path" or "Wildcard pattern".

[docker build document for local or tar](https://docs.docker.com/build/exporters/local-tar/)

# Syntax proposal
```shell
docker buildx build --output type=local[,parameters] .
```
```shell
docker buildx build --output type=tar[,parameters] .
```

## Parameters
`dest` (string) Path to copy files to
`targets` (list[string]) Select the path to export. Separated by a comma to select more than one (
`filters` (list[string]) The folder or file to export using the "Wild Path". Separated by a comma to select more than one

## Example
**Target one folder:**
```shell
docker buildx build --output type=local,targets=[targeted],dest=[dest] .
docker buildx build --output type=local,targets=/my/folder/targeted,dest=/my/dest .
```
**Target one folder version simplify,  for the default 'output' behavior without specifying the parameters:**
```shell
docker buildx build --output [target]:[dest] .
docker buildx build --output /my/folder/targeted:/my/dest .
``` 
**Target multi folder :**
```shell
docker buildx build --output type=local,targets=[target1,target2],dest=[dest] .
docker buildx build --output type=local,targets=/my/folder/targeted1,/my/folder/targeted2 .
```
**Target one folder and apply one filter (for selection only the file .log):**
```shell
docker buildx build --output type=local,targets=[target],filters=[filter],dest=[dest] .
docker buildx build --output type=local,targets=/my/folder/targeted1,filters=*.log,dest=/my/dest .
```
**Target one folder and apply one filter (for selection only the file .log) version simplify, for the default 'output' behavior without specifying the parameters):**
```shell
docker buildx build --output [target]:[filter]:[dest] .
docker buildx build --output /my/folder/targeted:*.log:/my/dest .
```
**Target multi folder and apply multi filters (for selection only the file .log and folder **/*-logs/**):**
```shell
docker buildx build --output type=local,targets=[target1,target2],filters=[filter1,filter2],dest=[dest] .
docker buildx build --output type=local,targets=/my/folder/targeted1,/my/folder/targeted2,filters=*.log,**/*-logs/**,dest=/my/dest .
``` 

## Note
The files are exported to the destination by following the relative path from the 'target' file where it was found. If several target files were specified then the output creates a folder in the output folder for each existing 'target' (with the name of the targeter folder)

## Next Step
If these functionalities are relevant, we can then imagine the negation of these two parameters with 'exlude-targets' and 'exlude-filters' using exactly the same syntax but with the aim of specifically excluding folders or files

**Comment by tonistiigi** [comment] 2024-07-26 21:43
duplicate of https://github.com/moby/buildkit/issues/874

**Closed by tonistiigi** 2024-07-26 21:43 UTC
