### ISSUE TITLE
proposal: generic remote driver

### ISSUE THREAD

**Issue by errordeveloper** [docker/buildx#893] opened 2021-12-20 12:02 UTC
Presently `docker-container` and `kubernetes` drivers rely on `buildx create` to setup underlying BuildKit deployment. It's possible for use to import a pre-existing deployment, which doesn't necessarily need to be created with `buildx create`, but it needs to align very closely with how `buildx create` deploys BuildKit. It would useful to have a more generic and flexible remote driver, that would also use TCP/TLS for communication, rather than `docker exec` or `pod/exec`.

There is a number of existing issues related to this topic, e.g.:
- https://github.com/docker/buildx/issues/859
- https://github.com/docker/buildx/issues/23

**Comment by tonistiigi** [comment] 2022-01-05 01:52
This seems to be a duplicate of https://github.com/docker/buildx/issues/23 . I added some more description to that issue and we can continue the discussion there.

**Closed by tonistiigi** 2022-01-05 01:52 UTC
Labels: enhancement, buildkit
