### ISSUE TITLE
Support BUILDKIT_HOST

### ISSUE THREAD

**Issue by lifeofguenter** [docker/buildx#276] opened 2020-05-05 12:28 UTC
Would be great if one could use buildx with an external buildkit host?

**Comment by tiborvass** [comment] 2020-05-07 03:42
Thanks for your request, I'm closing it as duplicate of https://github.com/docker/buildx/issues/23. Feel free to upvote it and continue the discussion there.

**Closed by tiborvass** 2020-05-07 03:42 UTC
