### ISSUE TITLE
buildx worker doesn't use host dns when `--driver-opt network=host ` is used

### ISSUE THREAD

**Issue by frezbo** [docker/buildx#1823] opened 2023-05-22 10:25 UTC
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/buildx/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [ ] ... the documentation does not mention anything about my problem
- [ ] ... there are no open or closed issues that are related to my problem

### Description

When using a buildx instance with `--driver-opt network=host ` the host dns servers are not used and public Google DNS servers are used:

Create two buildx workers
```bash
❯ docker buildx create --driver docker-container  --name normal --bootstrap 
```

```bash
❯ docker buildx create --driver docker-container --driver-opt network=host --name host --bootstrap
```

Build with both builders:

```bash
❯ docker buildx build --no-cache --platform=linux/amd64 --builder=normal --output=type=local,dest=_out .
[+] Building 13.2s (5/5) FINISHED                                                                                                                                                              
 => [internal] load .dockerignore                                                                                                                                                         0.1s
 => => transferring context: 2B                                                                                                                                                           0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                      0.1s
 => => transferring dockerfile: 84B                                                                                                                                                       0.0s
 => [internal] load metadata for docker.io/library/alpine:latest                                                                                                                         12.6s
 => CACHED [1/2] FROM docker.io/library/alpine@sha256:02bb6f428431fbc2809c5d1b41eab5a68350194fb508869a33cb1af4444c9b11                                                                    0.1s
 => => resolve docker.io/library/alpine@sha256:02bb6f428431fbc2809c5d1b41eab5a68350194fb508869a33cb1af4444c9b11                                                                           0.1s
 => ERROR [2/2] RUN cat /etc/resolv.conf && exit 1                                                                                                                                        0.3s
------                                                                                                                                                                                         
 > [2/2] RUN cat /etc/resolv.conf && exit 1:                                                                                                                                                   
#0 0.223 # This is /run/systemd/resolve/resolv.conf managed by man:systemd-resolved(8).                                                                                                        
#0 0.223 # Do not edit.                                                                                                                                                                        
#0 0.223 #                                                                                                                                                                                     
#0 0.223 # This file might be symlinked as /etc/resolv.conf. If you're looking at                                                                                                              
#0 0.223 # /etc/resolv.conf and seeing this text, you have followed the symlink.
#0 0.223 #
#0 0.223 # This is a dynamic resolv.conf file for connecting local clients directly to
#0 0.223 # all known uplink DNS servers. This file lists all configured search domains.
#0 0.223 #
#0 0.223 # Third party programs should typically not access this file directly, but only
#0 0.223 # through the symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a
#0 0.223 # different way, replace this symlink by a static file or a different symlink.
#0 0.223 #
#0 0.223 # See man:systemd-resolved.service(8) for details about the supported modes of
#0 0.223 # operation for /etc/resolv.conf.
#0 0.223 
#0 0.223 nameserver 192.168.30.1
#0 0.223 search frezbo.lan
------
Dockerfile:2
--------------------
   1 |     FROM alpine
   2 | >>> RUN cat /etc/resolv.conf && exit 1
   3 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cat /etc/resolv.conf && exit 1" did not complete successfully: exit code: 1
```

Builder with host network config

```bash
❯ docker buildx build --no-cache --platform=linux/amd64 --builder=host --output=type=local,dest=_out .
[+] Building 7.7s (5/5) FINISHED                                                                                                                                                               
 => [internal] load .dockerignore                                                                                                                                                         0.1s
 => => transferring context: 2B                                                                                                                                                           0.0s
 => [internal] load build definition from Dockerfile                                                                                                                                      0.0s
 => => transferring dockerfile: 84B                                                                                                                                                       0.0s
 => [internal] load metadata for docker.io/library/alpine:latest                                                                                                                          7.2s
 => CACHED [1/2] FROM docker.io/library/alpine@sha256:02bb6f428431fbc2809c5d1b41eab5a68350194fb508869a33cb1af4444c9b11                                                                    0.0s
 => => resolve docker.io/library/alpine@sha256:02bb6f428431fbc2809c5d1b41eab5a68350194fb508869a33cb1af4444c9b11                                                                           0.0s
 => ERROR [2/2] RUN cat /etc/resolv.conf && exit 1                                                                                                                                        0.2s
------                                                                                                                                                                                         
 > [2/2] RUN cat /etc/resolv.conf && exit 1:                                                                                                                                                   
#0 0.180                                                                                                                                                                                       
#0 0.180 nameserver 8.8.8.8                                                                                                                                                                    
#0 0.180 nameserver 8.8.4.4
#0 0.180 nameserver 2001:4860:4860::8888
#0 0.180 nameserver 2001:4860:4860::8844
------
Dockerfile:2
--------------------
   1 |     FROM alpine
   2 | >>> RUN cat /etc/resolv.conf && exit 1
   3 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c cat /etc/resolv.conf && exit 1" did not complete successfully: exit code: 1
```

### Expected behaviour

When using `--driver-opt network=host ` host dns servers to be used

### Actual behaviour

When using `--driver-opt network=host ` Google public dns servers used

### Buildx version

github.com/docker/buildx v0.10.4 c513d34

### Docker info

```text
❯ docker info
Client: Docker Engine - Community
 Version:    24.0.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.10.4
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.18.1
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 9
  Running: 8
  Paused: 0
  Stopped: 1
 Images: 9
 Server Version: 24.0.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.2.6-76060206-generic
 Operating System: Pop!_OS 22.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 30.57GiB
 Name: deepwater
 ID: G7YY:UWWD:GSQX:XFYO:AANM:AMWV:C67M:ZALZ:LRJ6:W4VX:H5YE:LBOV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Builders list

```text
❯ docker buildx ls
NAME/NODE       DRIVER/ENDPOINT                                                                                                                                            STATUS  BUILDKIT PLATFORMS
host            docker-container                                                                                                                                                            
  host0         unix:///var/run/docker.sock                                                                                                                                running v0.11.6  linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/arm64, linux/riscv64, linux/ppc64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
normal *        docker-container                                                                                                                                                            
  normal0       unix:///var/run/docker.sock                                                                                                                                running v0.11.6  linux/amd64, linux/amd64/v2, linux/amd64/v3, linux/arm64, linux/riscv64, linux/ppc64, linux/ppc64le, linux/s390x, linux/386, linux/mips64le, linux/mips64, linux/arm/v7, linux/arm/v6
```

### Configuration

```Dockerfile
FROM alpine
RUN cat /etc/resolv.conf && exit 1
```

**Comment by jedevc** [comment] 2023-05-22 10:28
This seems to be a duplicate of https://github.com/docker/buildx/issues/1688.

I'll close this one in preference of that, but if it's a different issue, feel free to re-open :heart:

**Closed by jedevc** 2023-05-22 10:28 UTC
Labels: status/triage

**Comment by frezbo** [comment] 2023-05-22 10:47
This is exactly the issue, I was looking at a different issue with dns, thanks for linking to the existing one
