### ISSUE TITLE
Global spaced ARG that results in aarch64 for linux/arm64 builds.

### ISSUE THREAD

**Issue by axblum** [docker/buildx#2002] opened 2023-08-10 15:47 UTC
### Description

I am currently trying to simplify a dockerfile that I have so it can be used for a multiplatform build. 

Ideally, I would be able to build to following dockerfile as follows. 
`docker build -f Dockerfile-t test --platform linux/arm64, linux/amd64`
```
FROM amazoncorretto:11
ARG SOME_AUTOMATIC_ARG #This would automatically pick aarch64 for amd64 builds
ADD ${SOME_AUTOMATIC_ARG} . 
```

I have found a number of solutions that result in using RUN, but it drastically increases the complexity of the dockerfile

**Comment by jedevc** [comment] 2023-08-10 15:55
`TARGETPLATFORM` sounds like roughly what you want: https://docs.docker.com/build/building/multi-platform/#cross-compilation

If that doesn't work, what's missing, what's the exact behaviour you're looking for?

**Comment by jedevc** [comment] 2023-08-10 16:17
Ah I've just seen https://github.com/docker/buildx/discussions/2001 (cc @crazy-max), that has some more context :smile:

**Comment by crazy-max** [comment] 2023-10-20 13:27
Duplicate of https://github.com/docker/buildx/discussions/2001

**Closed by crazy-max** 2023-10-20 13:27 UTC
Labels: kind/enhancement
