### ISSUE TITLE
Can't load base image from local `docker images` without registry

### ISSUE THREAD

**Issue by agirault** [docker/buildx#1453] opened 2022-12-06 16:36 UTC
## Related threads
- follow-up from #301 (single-arch)
- similar to #1386 (multi-arch)

## Issue 
We call the following command as it is the recommended step to test a container image before pushing it to a registry:
```fish
$ docker buildx build --platform $SINGLEARCH -t my_base_image --load .
```

A single platform build result will be exported to `docker images`, as [documented](https://docs.docker.com/engine/reference/commandline/buildx_build/#load):
```fish
$ docker images --format '{{.Repository}}' | grep my_base_image
my_base_image
```

Consider then this simple file named `final.dockerfile`:
```dockerfile
# syntax=docker/dockerfile:1
ARG BASE_IMAGE
FROM $BASE_IMAGE as base
```

We attempt to build this image using `my_base_image` as a base image with the command below:
```fish
docker buildx build --platform $SINGLEARCH -f final.dockerfile --build-arg BASE_IMAGE=my_base_image . 
``` 

Unlike `docker build`,  this will attempt to reach a registry (`docker.io/library` if there isn't one in the tag name) without using the cached image in `docker images`:

```
> [$SINGLEARCH internal] load metadata for docker.io/library/my_base_image:latest:
------
final.dockerfile:3
--------------------
   1 |     # syntax=docker/dockerfile:1
   2 |     ARG BASE_IMAGE
   3 | >>> FROM $BASE_IMAGE as base
   4 |     
--------------------
ERROR: failed to solve: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

The issue is similar if there is a registry url in the image name:
```
ERROR: failed to solve: your_registry.io: not found
```

Using `docker build` instead of `buildx` is not possible when building for another platform than the host platform.

## Questions

1. How do we use a docker image on the client (`docker images`) as a base image for a new single-arch buildx build?
2. If that's not possible from `--load/--output=type=docker`, can it be done with another client-side output type (local, tar, oci) without requiring a registry?
   - @jjlin suggested using a local registry [here](https://github.com/docker/buildx/issues/301#issuecomment-755164475) but it can open up other issues and might not be an acceptable solution for some

**Comment by crazy-max** [comment] 2022-12-07 09:59
This is expected as your container builder does not have access to the docker store. This will be solved with the containerd snapshotter on docker, see https://github.com/docker/roadmap/issues/371. This is also similar to https://github.com/docker/buildx/issues/166. In the meantime you can push this image to a registry.

Also if you just want to build a single platform you can just use the default `docker` builder:

```
$ docker buildx use default
$ docker buildx build --platform linux/amd64 -t my_base_image .
$ docker buildx build --platform linux/amd64 -f final.dockerfile --build-arg BASE_IMAGE=my_base_image . 
```

**Comment by jiangtao69039** [comment] 2023-10-13 10:23
I'm running into the same issue.  Is there any solution now?  @agirault

**Comment by jedevc** [comment] 2023-10-13 10:44
This issue is a duplicate of https://github.com/moby/buildkit/issues/2343, so I'm going to close this issue in preference of that one - that one also has more discussion there.

**Closed by jedevc** 2023-10-13 10:44 UTC
