### ISSUE TITLE
Bake: Apply a template to 'all other targets'

### ISSUE THREAD

**Issue by ciaranmcnulty** [docker/buildx#1149] opened 2022-06-02 13:05 UTC
To give some context I work on web applications a fair bit and commonly have a mix of Yaml and HCL, where local users are just using compose, and bake is used in CI for more advanced building.

So we might run in CI `docker buildx bake -f docker-compose.yml -f docker-bake.ci.hcl` where the the HCL is using CI env vars:

```hcl
target "web" {
    tags = [
        "${CI_REGISTRY}/myproj/web:sha-${CI_COMMIT_SHA}",
        "${CI_REGISTRY}/myproj/web:branch-${CI_COMMIT_REF}",
        notequals("", "${CI_RELEASE_TAG}") ? "${CI_REGISTRY}/myproc/web:tag-${CI_RELEASE_TAG}" : "",
        [... lots more...]
    ]
    cache-to = [
        "type=registry,mode=max,ref=${CI_REGISTRY}/myproj/web:cache-${CI_DEFAULT_BRANCH}",
    ]
    cache-from = [
        "type=registry,ref=${CI_REGISTRY}/myproj/web:cache-${CI_DEFAULT_BRANCH}",
        "type=registry,ref=${CI_REGISTRY}/myproj/web:cache-${CI_COMMIT_REF}",
    ]
}

target "db" {
   [... same again ..]
}


[... more targets ...]
```

(I'm aware I can compress the tag/cache-to/cache-from by using user-defined functions in future)

My issue is that if a service is added to the Yaml, it also needs to be able to be added to the HCL too. Really I'd like to just have one target in the HCL, because all that's varying is the target name

Is there a sensible way to avoid this repetition?

**Comment by ciaranmcnulty** [comment] 2022-06-02 14:48
I guess part of this is some way to access the target name?

```hcl
target "_common" {
    tags = [
        "${CI_REGISTRY}/myproj/${TARGET_NAME}:sha-${CI_COMMIT_SHA}",
    ]
}
```

Then I could maybe `--set=*.inherits=[common]` ?

**Comment by tonistiigi** [comment] 2022-06-03 17:36
dupe of https://github.com/docker/buildx/issues/956 ?

**Closed** 2022-06-03 21:48 UTC
