### ISSUE TITLE
Option to disable platform output namespace?

### ISSUE THREAD

**Issue by cpuguy83** [docker/buildx#158] opened 2019-10-03 18:15 UTC
I have some some build targets setup for multiple platforms which takes care of namespacing outputs itself e.g. `COPY --from=build /path/to/build/bin/* /bin/${TARGETPLATFORM}/`

However when building with buildx and multiple platforms (and seemingly only multiple platforms?) buildx namespaces further as `<TARGETOS>_<TARGETARCH>[_<TARGEVARIANT>]/<OUTPUT>/` which ends up being redundant and requires an extra merge step.

Hoping to have some flag or some way to signal to not do the top-level namespacing.

**Comment by tonistiigi** [comment] 2019-10-05 00:17
This sounds simple but isn't that easy to achieve. The issue is in handling duplicate files and controlling file order. On local file sync and tar exporter there is no copy that creates a duplicate for the merged files. Instead all the platforms are handled separately from their original snapshots. I'd recommend `buildx build -o - | tar x --strip-components=1`

If someone can implement it without degrading performance and adding lot of complexity I'm not against a flag.

**Comment by tonistiigi** [comment] 2019-10-05 00:26
tbh, it isn't impossibly complicated. For local exporter, assuming retransmitting duplicates is ok,  the biggest change is that exporting can't happen in parallel for a deterministic result. For tar exporter smth. like `MergedFS([]FS) FS` implementation is needed similar to https://github.com/tonistiigi/fsutil/blob/3bbb99cdbd76619ab717299830c60f6f2a533a6b/fs.go#L47 that joins separate walkers into one.

**Closed** 2020-12-08 23:00 UTC
