### ISSUE TITLE
Use an existing buildkit deployment

### ISSUE THREAD

**Issue by andrewrynhard** [docker/buildx#216] opened 2019-12-24 12:29 UTC
It is a little difficult to use the kubernetes driver in CI. Well, maybe in our CI it is. The short version is that we are using drone running in kubernetes. Drone does not have a clean way for us to get the permissions required to run `docker buildx inspect —boostrap`. We managed to get it working, but it would be more secure if the jobs didn’t have to have permissions to create the buildkit deployment. Scoping the run to only needing deployment list, pod list and pod/exec permissions would be an improvement. Is there a way to have buildx use an externally managed set of buildkit pods?

**Comment by AkihiroSuda** [comment] 2020-01-01 17:02
`buildctl` already supports this, though `buildx` doesn't support this yet

```
buildctl \
  --addr kube-pod://buildkitd \
  build --frontend dockerfile.v0 --local context=/path/to/dir --local dockerfile=/path/to/dir
```
https://github.com/moby/buildkit/tree/master/examples/kubernetes

**Comment by tiborvass** [comment] 2020-02-05 22:28
Duplicate of https://github.com/docker/buildx/issues/23

**Closed by tiborvass** 2020-02-05 22:28 UTC
Labels: enhancement, kubernetes
