### ISSUE TITLE
Tag not included in manifest for single-platform docker buildx build with OCI output

### ISSUE THREAD

**Issue by chadlwilson** [docker/buildx#1659] opened 2023-03-02 15:37 UTC
### Description

When you do a `docker buildx build --tag helloworld:latest --output type=oci,dest=my-oci.tar .` for a single platform image, buildx includes a `manifest.json` alongside the `oci-layout` allowing it to be directly `docker load`ed at a later date.

However surprisingly it does not seem to include the `--tag` you specify in the `manifest.json`'s `RepoTags` (always seems to be `"RepoTags":null`), meaning a direct `docker load` will get you an anonymous image.

This seems unexpected, so might be a bug - but will be charitable and consider this a feature request. It'd be convenient for the `--tag` to be reflected in the export where possible. (my understanding is that this is not possible for the generic OCI layout tarballs required for multi-platform images)

**Comment by jedevc** [comment] 2023-03-03 09:32
Managed to reproduce this, the issue is in BuildKit - this looks like a duplicate of https://github.com/moby/buildkit/issues/1949, which I'll try and follow-up on :tada:

**Closed by jedevc** 2023-03-03 09:32 UTC
Labels: kind/enhancement, status/triage

**Comment by chadlwilson** [comment] 2023-03-03 10:10
Thanks @jedevc - will follow that!
