### ISSUE TITLE
Platforms attribute is getting lost in multi-level inheritance in bake files

### ISSUE THREAD

**Issue by sandhose** [docker/buildx#923] opened 2022-01-19 18:30 UTC
When two targets inherit from the same target, which itself inherit from another base target are in a group, the `platform` attributes is getting lost on one of them.

Put it in another way:
 - I have a `A` target, which has a `platforms` attribute
 - I have a `B` target, which inherits on `A`
 - I have `C` and `D` targets which both inherit from `B`
 - When `C` and `D` are put in a group, `C` properly inherits the `platforms` attribute, but `D` does not

Sample bake file to reproduce `docker-bake.hcl`:

```hcl
group "default" { targets = ["C", "D"] }

target "A" {
  platforms = [
    "linux/amd64",
    "linux/arm64",
    "linux/arm",
  ]
}

target "B" {
  inherits = ["A"]
}

target "C" {
  inherits = ["B"]
}

target "D" {
  inherits = ["B"]
}
```

Running `docker buildx bake --print` yields:

```json
{
  "group": {
    "default": {
      "targets": [
        "C",
        "D"
      ]
    }
  },
  "target": {
    "C": {
      "context": ".",
      "dockerfile": "Dockerfile",
      "platforms": [
        "linux/amd64",
        "linux/arm64",
        "linux/arm"
      ]
    },
    "D": {
      "context": ".",
      "dockerfile": "Dockerfile"
    }
  }
}
```

while it should output:

```json
{
  "group": {
    "default": {
      "targets": [
        "C",
        "D"
      ]
    }
  },
  "target": {
    "C": {
      "context": ".",
      "dockerfile": "Dockerfile",
      "platforms": [
        "linux/amd64",
        "linux/arm64",
        "linux/arm"
      ]
    },
    "D": {
      "context": ".",
      "dockerfile": "Dockerfile",
      "platforms": [
        "linux/amd64",
        "linux/arm64",
        "linux/arm"
      ]
    }
  }
}
```

I haven't tested with other attributes, but they might have issues as well.

Note that setting the platform in the `B` target (so only one level of inheritance) intead of `A` works.

**Comment by tonistiigi** [comment] 2022-01-19 20:35
Looks like duplicate of #912

**Closed by tonistiigi** 2022-01-19 20:35 UTC

**Comment by sandhose** [comment] 2022-01-20 10:04
Ugh, I was looking for an existing issue, but forgot to check closed ones :facepalm: 
Anyway, glad to see it's already fixed, thanks!
