### ISSUE TITLE
'docker build' error: "failed to solve with frontend dockerfile.v0"

### ISSUE THREAD

**Issue by nromagno** [docker/buildx#415] opened 2020-10-15 12:59 UTC
- [x] I have tried with the latest version of my channel (Stable or Edge)
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: DAA27533-4D93-4AF4-916C-8492CC6BF66B/20201015121621
 
### Expected behavior
I expect to build a docker image from my Dockerfile for my R Shiny application.

### Actual behavior
I get the resulting error from the docker build command:
![Capture](https://user-images.githubusercontent.com/27997570/96128345-82d97d80-0ef5-11eb-8016-1e1b6bf43741.PNG)

### Information
Docker version is:
![Capture](https://user-images.githubusercontent.com/27997570/96128670-f24f6d00-0ef5-11eb-80cd-70f8710ca89d.PNG)

Windows Version: **Windows 10 Home, version 1909**

And `docker run hello-world` does work as expected:
![Capture](https://user-images.githubusercontent.com/27997570/96128545-ca600980-0ef5-11eb-87d3-0ec1016751d7.PNG)

I'm working with **Docker Desktop for Windows 10 Home** and I've followed this guide for the installation:
[Install Docker Desktop on Windows Home](https://docs.docker.com/docker-for-windows/install-windows-home/)

Since I think I have followed the guide correctly, and passed the `docker run hello-world` test, I'm not sure how to begin debugging this error. 

I would really appreciate any help on clarifying what the error means, and how to potentially address it. Thank you!

**Comment by tonistiigi** [comment] 2020-10-16 03:19
Please post `docker version` and a reproducer. Also, check if there is anything interesting in the daemon logs.

**Comment by julioR4mirez** [comment] 2020-10-19 03:25
I had the same error, my issue was the name of the file `dockerfile`, I changed the name to `Dockerfile `and it worked.

**Comment by nromagno** [comment] 2020-10-19 15:54
@tonistiigi my docker version is:
Docker version 19.03.13

Also, by reproducer, do you mean a reproducible example? 

And for the daemon logs you suggested, I'm not sure if I have been able to locate them correctly. I followed the advice [here](https://docs.docker.com/config/daemon/#read-the-logs) on where to find them (on my Windows it was under `AppData\Local\Docker` and I found this [log.txt](https://github.com/docker/buildx/files/5403077/log.txt) file. 

I looked through the log.txt file but I couldn't find anything helpful. 

Is this the correct file? And did I miss something important within it?

**Comment by karol93** [comment] 2020-10-19 18:12
I have the same problem on Docker version 19.03.13, build 4484c46d9d

**Comment by Muqito** [comment] 2020-10-21 18:47
I noticed this as well with the same version after the update

**Comment by ArifIstaka** [comment] 2020-10-26 15:02
Name the file Dockerfile exactly.

**Comment by UlasKasim** [comment] 2020-10-27 14:23
changing name 'Dockerfile' from 'dockerfile' also worked for me

**Comment by nromagno** [comment] 2020-10-27 14:49
@UlasKasim @ArifIstaka the name of the file is already capitalized. 
![Capture](https://user-images.githubusercontent.com/27997570/97318019-b4dece00-186b-11eb-842e-b5a02fd728f5.PNG)

@Muqito Can you clarify a little bit on how you "purged the settings and restarted." Thanks!

**Comment by Muqito** [comment] 2020-10-27 15:22
@nromagno Sure thing.

Click on this little bug icon up to the right, and then you'll see the following settings:


![purge-and-reset](https://user-images.githubusercontent.com/3002925/97322830-7ac3fb00-1870-11eb-802d-64bc347c74f1.PNG)

**Comment by nromagno** [comment] 2020-10-27 16:20
@Muqito I purged the data and restarted as you described, but unfortunately the same error still appears.

**Comment by Kusanagi-2029** [comment] 2020-10-27 18:42
@Muqito, I have the same error in the case, so should we be waiting for some fixies on windows?

**Comment by Kusanagi-2029** [comment] 2020-10-28 10:07
@stephen-turner, @tonistiigi, @nromagno, Good afternoon! I am new to Docker. I try to run the image and container based on it by reading the Microsoft documentation step by step:
    https://docs.microsoft.com/ru-ru/dotnet/core/docker/build-container?tabs=windows
But if I specify a Dockerfile without an extension, then I encounter an error reading Dockerfile by Docker itself (for some reason, it does not see the Dockerfile in this directory). When I specify the .txt extension (docker build -t counter-image -f Dockerfile.txt .
), Docker sees this file:
![docker-error 5](https://user-images.githubusercontent.com/71845085/97420467-66d5d300-191c-11eb-8c7c-a72ac78d0c51.PNG)
![docker-error 6](https://user-images.githubusercontent.com/71845085/97420473-68070000-191c-11eb-9c60-70ab3e45419d.PNG)
![docker-error 8](https://user-images.githubusercontent.com/71845085/97421550-b36dde00-191d-11eb-92b9-af64b0c9e0d8.PNG)
![docker-error 7](https://user-images.githubusercontent.com/71845085/97420478-689f9680-191c-11eb-8250-97a86a1420d1.PNG)

So do I not understand something due to lack of experience, or is there really some problem? 
     
     Best regards, Kusanagi-2029

**Comment by bravecobra** [comment] 2020-10-31 16:08
I just hit the same issue. I use the WSL2 engine, which is of course case-sensitive. The command sent to docker from Visual Studio is specifying a fully lowercase path, which breaks the command of course.

**Comment by llwydsj** [comment] 2020-11-01 12:06
> I just hit the same issue. I use the WSL2 engine, which is of course case-sensitive. The command sent to docker from Visual Studio is specifying a fully lowercase path, which breaks the command of course.

Same here. Visual Studio debugging with Docker works fine. Output windows shows:
`>docker build -f "C:\dev\src\Project.Name\Dockerfile" args...`
But building from the context menu when right clicking on the Dockerfile in the solution explorer executes this:
`>docker build -f "c:\dev\src\project.name\dockerfile" args...`

**Comment by bette** [comment] 2020-11-04 19:16
This *may* help someone else:
The instructions say to make sure you are in the directory "node-bulletin-board/bulletin-board-app" and I was getting the above error when running in "node-bulletin-board". Changed into the bulletin-board-app child directory and it ran. Naturally I only re-read the doc after trying everything else.

**Comment by Pranav021** [comment] 2020-11-09 03:43
Simply change name of  "dockerfile" to "Dockerfile" and then build, it works for me.

**Comment by tonistiigi** [comment] 2020-11-09 04:27
These reports seem to be unique for windows. Afaics NTFS is a case-sensitive filesystem so I'm not sure how having Dockerfile in the wrong case producing an error could be a regression and not just an expected result. If someone can show the exact reproduction steps that show something that previously worked not working anymore in buildx it is possible we could do something about it or improve documentation.

**Comment by stephen-turner** [comment] 2020-11-09 09:12
I don't know if it's a regression from old build, but I would say that it's highly unexpected for `dockerfile` and `Dockerfile` to behave differently on a typical Windows machine.

**Comment by DanieleB89** [comment] 2020-11-13 13:10
![image](https://user-images.githubusercontent.com/45817471/99075556-f684ae00-25b9-11eb-9f4c-56f1eacc7e09.png)

**Comment by c0ri** [comment] 2020-11-15 06:25
Same here:
failed to solve with frontend dockerfile.v0: failed to build LLB: 
$ docker --version
Docker version 19.03.13, build 4484c46d9d

**Comment by tonistiigi** [comment] 2020-11-15 06:35
> I don't know if it's a regression from old build, but I would say that it's highly unexpected for dockerfile and Dockerfile to behave differently on a typical Windows machine.

It's not too unexpected as I'm 99% sure that if you would just create a tarball of your build context and send it to the daemon (simplified version on how the API works) it would fail with any version of the builder. There is some preprocessing specifically for this file and that's why the casing is masked. For any other file referred to in Dockerfile no such exception exists as well. These are all linux container builds that are referred here and (common) Linux filesystems are case sensitive.

**Comment by pythiantech** [comment] 2020-11-16 04:16
Same here:
`failed to solve with frontend dockerfile.v0: failed to build LLB: error from sender: context created`
Docker version:
Docker version 19.03.13, build 4484c46d9d

**Comment by tonistiigi** [comment] 2020-11-16 04:18
The solution is in https://github.com/docker/buildx/issues/415#issuecomment-716606000

**Comment by pythiantech** [comment] 2020-11-16 04:20
The Dockerfile is named "Dockerfile". I have also tried purging and restarting but the issue persists.

**Comment by amankkg** [comment] 2020-11-16 11:07
@tonistiigi filename is not the only issue here, or I have just another bug

Renaming `credsStore` to `credStore` in `~/.docker/config.json` is what helped me actually, but it seems like Docker Destkop keeps adding `credsStore` entry in that config file

**Comment by mrmariush** [comment] 2020-11-18 19:02
I Solved problem.
Just Sgin in in your Docker account

**Comment by mrmariush** [comment] 2020-11-18 19:04
> 
> 
> ![image](https://user-images.githubusercontent.com/45817471/99075556-f684ae00-25b9-11eb-9f4c-56f1eacc7e09.png)
> even the tutorial in a fresh Docker Desktop installation fails...

I had this same problem.
Just Sgin in in your Docker account

**Comment by nromagno** [comment] 2020-11-18 20:34
@llwydsj can you expand a little bit on your comment and the how you suggested to resolve this issue? I'm not familiar with Visual Studio, so how could I check if my issue also arises from case sensitivity. Thanks!

**Comment by tonistiigi** [comment] 2020-11-19 21:48
I did some digging and it turned out this was not even caused by the case-sensitivity of the filesystem. There is a special fallback that allows name `dockerfile` when loading `Dockerfile` fails. It is only valid for this name and only for `dockerfile` name, eg. `dockerfilE` will not work.

I've provided patches in buildx https://github.com/docker/buildx/pull/444 and also in Dockerfile frontend in Buildkit https://github.com/moby/buildkit/pull/1816 to maintain compatibility. Only one of them is needed to have the old behavior back.

**Comment by therealsohail** [comment] 2020-11-25 12:32
Rename dockerfile to Dockerfile. Doing this fixed my issue.

**Comment by normjon** [comment] 2020-11-25 21:45
I had the same issue (on a Mac).  running a test from my home directory /Users/norm
docker build -t test .
[+] Building 0.0s (2/2) FINISHED                                                
 => ERROR [internal] load .dockerignore                                    0.0s
 => => transferring context: 40B                                           0.0s
 => ERROR [internal] load build definition from Dockerfile                 0.0s
 => => transferring dockerfile: 40B                                        0.0s
------
 > [internal] load .dockerignore:
------
------
 > [internal] load build definition from Dockerfile:
------
failed to solve with frontend dockerfile.v0: failed to build LLB: error from sender: open .Trash: operation not permitted

I moved the Dockerfile out of my home directory into a subdirectory (/Users/norm/test/) and was able to build without the above error when executed from /Users/norm/test/.  Seems permission related

**Comment by thaJeztah** [comment] 2020-11-26 00:35
> I moved the Dockerfile out of my home directory into a subdirectory (/Users/norm/test/) and was able to build without the above error when executed from /Users/norm/test/. Seems permission related`

Yes, that situation is expected; always start builds from a directory that only contains files that you need for your build.

When you run `docker build .`, the last `.` is the path of the "build context" (in case of a `.` that's the current directory). Running a build will send the build context and all files and subdirectories to the daemon, so that they can be used as part of your build (sending your entire home directory is likely not what you want 😅)

Buildkit is smarter in that it only sends files that are used by a `COPY` or `ADD` instruction in your Dockerfile, but it may still scan the directory for file changes (and in your case run in permission issued)

**Comment by fanpero87** [comment] 2020-11-26 15:18
> 
> 
> changing name 'Dockerfile' from 'dockerfile' also worked for me

Hello,
Where can I find this file?
I'm trying on a Mac and Windows computer and is the same error and I cannot find that file.

Thanks.

**Comment by thaJeztah** [comment] 2020-11-26 15:28
The Dockerfile is a file you create yourself if you want to build an image: https://docs.docker.com/get-started/part2/

**Comment by bravecobra** [comment] 2020-11-27 17:34
> changing name 'Dockerfile' from 'dockerfile' also worked for me

Funny, for me the fix is the other way round....I don't think we have found the culprit yet

**Comment by bravecobra** [comment] 2020-12-01 15:52
Apparently this issue (or at least the one I'm experiencing) is already known with the visual studio people and the fix is pending release: https://developercommunity.visualstudio.com/content/problem/1192625/build-docker-image-failing-because-of-lowercased-d.html

**Comment by antoniofruci** [comment] 2020-12-02 08:50
Hi, I had the same issue and I could finally solve it by disabling buildkit feature as explained here: https://stackoverflow.com/questions/64382812/docker-has-the-same-error-regardless-of-what-i-try-to-build-windows-10

**Comment by pythiantech** [comment] 2020-12-02 12:43
> Hi, I had the same issue and I could finally solve it by disabling buildkit feature as explained here: https://stackoverflow.com/questions/64382812/docker-has-the-same-error-regardless-of-what-i-try-to-build-windows-10

Worked for me, thanks

**Comment by thaJeztah** [comment] 2020-12-02 14:52
The lowercase dockerfile issue will be fixed by https://github.com/docker/buildx/pull/444, which adds a fallback to check both for `Dockerfile` and `dockerfile` for backward-compatibility with the classic builder, which had that fallback in place. (note that other cases, such as `dOCkerFile` _won't_ be supported

Note that other errors starting with `failed to solve with frontend dockerfile.v0` may be unrelated; the `failed to solve.. ` prefix is a generic prefix for this part of builds, and the errors _after that_ are the underlying error, so if you run into another issue and think it's a bug, please open a new ticket instead.

**Comment by JuniorAguilera** [comment] 2020-12-03 15:16
Details:
Windows 10 Pro
Docker version : 19.03.13
I try to change the name:
Dockerfile.dockerfile
I delete ".dockerfile"... so
"dockerfile" not extension... It's working now...

**Closed** 2020-12-04 01:54 UTC

**Comment by UsmanAsifTaqi** [comment] 2020-12-04 06:11
> @stephen-turner, @tonistiigi, @nromagno, Good afternoon! I am new to Docker. I try to run the image and container based on it by reading the Microsoft documentation step by step:
> https://docs.microsoft.com/ru-ru/dotnet/core/docker/build-container?tabs=windows
> But if I specify a Dockerfile without an extension, then I encounter an error reading Dockerfile by Docker itself (for some reason, it does not see the Dockerfile in this directory). When I specify the .txt extension (docker build -t counter-image -f Dockerfile.txt .
> ), Docker sees this file:
> ![docker-error 5](https://user-images.githubusercontent.com/71845085/97420467-66d5d300-191c-11eb-8c7c-a72ac78d0c51.PNG)
> ![docker-error 6](https://user-images.githubusercontent.com/71845085/97420473-68070000-191c-11eb-9c60-70ab3e45419d.PNG)
> ![docker-error 8](https://user-images.githubusercontent.com/71845085/97421550-b36dde00-191d-11eb-92b9-af64b0c9e0d8.PNG)
> ![docker-error 7](https://user-images.githubusercontent.com/71845085/97420478-689f9680-191c-11eb-8250-97a86a1420d1.PNG)
> 
> So do I not understand something due to lack of experience, or is there really some problem?
> 
> ```
>  Best regards, Kusanagi-2029
> ```

I have encountered the same problem after some searching I luckily found that using Dockerfile with Extention will do the trick 
Instead of Doing this
**docker build -t hello-world -f Dockerfile .**
I fave changed this to 
**docker build -t hello-world -f Dockerfile .txt .**

**Comment by darkrift** [comment] 2020-12-04 17:39
So I was having this problem on my mac, and it tuns out that there was a docker temp file in the current folder. Deleting it solved it. Here's the error and the file in question : 

Exception :
`failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to build LLB: Error processing tar file(exit status 1): unexpected EOF`

File :
`-rw-------   1 rlavoie  1177235957  2428567552  4 Dec 00:10 .docker_temp_499366070`

**Comment by V4A001** [comment] 2020-12-06 23:48
Same error here, when is there a solution ? Kubernetes, docker and visual studio 2019..a lot of bugs and weird things. Can it become a steady working environment to work in?

**Comment by thaJeztah** [comment] 2020-12-07 12:43
@V4A001 what is "same error"? If it's because of a lowercase `dockerfile`, rename the file to `Dockerfile` to fix the problem. "lots of bugs and weird things" is not very helpful; also see https://github.com/docker/buildx/issues/415#issuecomment-737279041

> Note that other errors starting with `failed to solve with frontend dockerfile.v0` may be unrelated; the `failed to solve.. ` prefix is a generic prefix for this part of builds, and the errors _after that_ are the underlying error, so if you run into another issue and think it's a bug, please open a new ticket instead.

**Comment by V4A001** [comment] 2020-12-07 14:50
It seems OO-design is lacking with throws same bug at various places? If I use in VS 2019 the debugger to build a docker images that works fine with Docker file (capital first letter). If I right click on the Docker file and do 'Build Docker Image' it fails see below. If I change to lower caps it builds.

`
8>failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount840562661/dockerfile: no such file or directory
8>d:\projects\-\dockerfile : error CTC1014: Docker command failed with exit code 1.
8>d:\projects\-\dockerfile : error CTC1014: #1 [internal] load .dockerignore
8>d:\projects\-\dockerfile : error CTC1014: #1 transferring context: 35B done
8>d:\projects\-\dockerfile : error CTC1014: #1 DONE 0.0s
8>d:\projects\-\dockerfile : error CTC1014: 
8>d:\projects\-\dockerfile : error CTC1014: #2 [internal] load build definition from dockerfile
8>d:\projects\-\dockerfile : error CTC1014: #2 transferring dockerfile: 2B done
8>d:\projects\-\dockerfile : error CTC1014: #2 DONE 0.0s
8>d:\projects\-\dockerfile : error CTC1014: failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount840562661/dockerfile: no such file or directory

`

**Comment by Geremie** [comment] 2020-12-08 01:21
> > Hi, I had the same issue and I could finally solve it by disabling buildkit feature as explained here: https://stackoverflow.com/questions/64382812/docker-has-the-same-error-regardless-of-what-i-try-to-build-windows-10
> 
> Worked for me, thanks

Worked for me as well, many thanks

**Comment by thaJeztah** [comment] 2020-12-08 13:04
@V4A001 

> failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount840562661/dockerfile: no such file or directory

When you mention "If I right click on the Docker file and do 'Build Docker Image' it fails see below. If I change to lower caps it builds."; is the Dockerfile your building named `Dockerfile` or `dockerfile`? 

Note that the while fix in buildx that was merged is on "master", it's not in a released version yet. I also don't know how the `Build Docker Image` option is implemented in VScode, which could play a role here.

**Comment by V4A001** [comment] 2020-12-08 15:09
The debugger of debugger itself works with Dockerfile
The right click on the file to build the image only works if the file is dockerfile

**Comment by nromagno** [comment] 2020-12-20 19:40
> Hi, I had the same issue and I could finally solve it by disabling buildkit feature as explained here: https://stackoverflow.com/questions/64382812/docker-has-the-same-error-regardless-of-what-i-try-to-build-windows-10

I tired this and it finally worked! thanks!

**Comment by bhuvmhz** [comment] 2020-12-22 07:18
I tried many options but unfortunately didn't helped, and I realized that my `Dockerfile` was mistakenly inside ` /app/src`,  moved `Dockerfile` to root, and it just WORKED!! 💯 

```
FROM node:latest

RUN mkdir -p /app/src

WORKDIR /app/src

COPY package.json .

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "start"]

```

**Comment by doomlancer** [comment] 2020-12-28 22:55
> Hi, I had the same issue and I could finally solve it by disabling buildkit feature as explained here: https://stackoverflow.com/questions/64382812/docker-has-the-same-error-regardless-of-what-i-try-to-build-windows-10

this worked for me. thanks!

**Comment by IsabelLafaia** [comment] 2020-12-29 09:12
For me it worked placing the Dockerfile (capitalised) inside a folder, and then running `docker image build ./[foldername]`

**Comment by Devnol** [comment] 2021-01-04 10:26
Same issue with Github Actions ubuntu-latest. https://github.com/Cytrus-RE/debia/runs/1643130474?check_suite_focus=true

**Comment by Devnol** [comment] 2021-01-04 10:59
It only appears to only break if I attempt to cross-build for an architecture such as armv7 or anything that isn't x86/64

**Comment by Devnol** [comment] 2021-01-04 10:59
I had that issue on my mac as well

**Comment by Peter-Schorn** [comment] 2021-01-09 08:26
on macOS renaming "DockerFile" to "dockerfile" fixed the problem for me.

**Comment by Devnol** [comment] 2021-01-09 10:40
My file was named "Dockerfile" and building only for amd64 with the default build system worked fine. When I used buildx to build for a different architecture it would error out.

**Comment by mariancraciun1983** [comment] 2021-01-16 05:18
Another situation that I encountered was that `.dockerignore` was blocking the COPY . For example: 

# dockerfile:
```
FROM nginx:1.19.6-alpine as nginx
COPY ./Build/release/authenticator/conf/nginx.conf /etc/nginx/conf.d/default.conf
```
error:
```
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = failed to build LLB: failed to compute cache key: "/Build/release/authenticator/conf/nginx.conf" not found: not found
```


The solution was to add `!/Build/release/authenticator/conf/nginx.conf` in  `.dockerignore`

**Comment by Xandrak** [comment] 2021-01-17 18:29
> 
> 
> @tonistiigi file name is not the only issue here, or I have just another bug
> 
> Here is what I face when running `docker build` command:
> 
> ```shell
> failed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: rpc error: code = Unknown desc = error getting credentials - err: exec: "docker-credential-desktop.exe": executable file not found in $PATH, out: ``
> ```
> 
> Renaming `"credsStore": "desktop.exe"` to `"credStore": "desktop.exe"` in `~/.docker/config.json` is what helped me actually, but it seems like Docker Destkop keeps adding `credsStore` entry in that config file

Crazy, this worked for me. Thanks!

Win 10 Pro WSL2 Ubuntu 20.04

**Comment by tonistiigi** [comment] 2021-01-18 03:50
No such thing as `credStore` config key. https://github.com/docker/cli/blob/master/cli/config/configfile/file.go#L37

**Comment by thaJeztah** [comment] 2021-01-18 12:56
Renaming `credsStore` to `credStore` would be the equivalent to _removing_ the `credsStore` config (which makes docker skip the credentials-helper, and to store credentials as base64 encoded plain text in the configuration file).

**Comment by HamedNN76** [comment] 2021-01-26 23:26
restarting docker worked for me

**Comment by ww9** [comment] 2021-01-29 15:54
Deleting docker config file from inside WSL2 ubuntu shell fixed it for me:

`rm ~/.docker/config.json`

**Comment by RGA052** [comment] 2021-01-29 16:40
My issue was regarding the permissions to download the FROM image

I ran the docker build  command as following:

`sudo docker build -t myapp .`

Also the docker file was named 'Dockerfile'

That worked for me

**Comment by jaroslavtyc** [comment] 2021-02-05 12:01
Well, docker message **is** confusing.
In my case I just used **invalid working directory** (so I just have to `cd` to the right subdir with my Dockerfile).

Instead of explaining message like "No Dockerfile found, looked at current working directory /foo/bar" on my `docker build --no-cache --tag jaroslavtyc/pb-web:8.0 .` command I saw 

```bash
[+] Building 0.0s (2/2) FINISHED                                                                                                                                                                                                        
 => [internal] load build definition from Dockerfile                                                                                                                                                                               0.0s
 => => transferring dockerfile: 2B                                                                                                                                                                                                 0.0s
 => CANCELED [internal] load .dockerignore                                                                                                                                                                                         0.0s
 => => transferring context:                                                                                                                                                                                                       0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount710040659/Dockerfile: no such file or directory
```

**Comment by James-sss** [comment] 2021-02-13 19:49
Window 10 Home restart worked for me 
![Screenshot (79)](https://user-images.githubusercontent.com/53993050/107859910-45eeaa80-6e45-11eb-901b-e1050787cb99.png)

**Comment by mariusdkm** [comment] 2021-02-18 10:22
For anyone stumbling across this issue on mac...
`failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = failed to parse /Users/myusername/.docker/.token_seed: unexpected end of JSON input`

I just deleted `.token_seed` and `.token_seed.lock` inside of `/Users/myusename/.docker`

**Comment by thaJeztah** [comment] 2021-02-18 13:30
@mariusdkm could you open a new ticket for that?

**Comment by JesielPalacios** [comment] 2021-02-20 03:43
Great..

$ docker build . -t spa-react:1.0
[+] Building 12.0s (8/12)
 => [internal] load build definition from Dockerfile                                                                                                                               0.9s 
 => => transferring dockerfile: 552B                                                                                                                                               0.0s 
 => [internal] load .dockerignore                                                                                                                                                  0.6s 
 => => transferring context: 2B                                                                                                                                                    0.0s 
 => [internal] load metadata for docker.io/library/nginx:1.19.6                                                                                                                    0.0s 
 => [internal] load metadata for docker.io/library/node:15.8.0                                                                                                                     0.0s 
 => [node-server 1/5] FROM docker.io/library/node:15.8.0                                                                                                                           0.0s 
 => ERROR [internal] load build context                                                                                                                                           11.0s 
 => => transferring context: 81.80MB                                                                                                                                              10.8s 
 => CACHED [client-app 1/2] FROM docker.io/library/nginx:1.19.6                                                                                                                    0.0s 
 => CACHED [node-server 2/5] WORKDIR /usr/src/app                                                                                                                                  0.0s 
------
 > [internal] load build context:
------
failed to solve with frontend dockerfile.v0: failed to build LLB: error from sender: open node_modules\eslint-plugin-testing-library\node_modules\@typescript-eslint\experimental-utils\_ts3.4\dist\ts-eslint-scope: Access is denied

**Comment by thaJeztah** [comment] 2021-02-20 09:57
@JesielPalacios looks unrelated; from the error it looks like you don't have permissions to read a file in your build context;

```
error from sender:
open node_modules\eslint-plugin-testing-library\node_modules\@typescript-eslint\experimental-utils\_ts3.4\dist\ts-eslint-scope:
Access is denied
```

see https://github.com/docker/buildx/issues/415#issuecomment-737279041

> Note that other errors starting with `failed to solve with frontend dockerfile.v0` may be unrelated; the `failed to solve.. ` prefix is a generic prefix for this part of builds, and the errors _after that_ are the underlying error,

**Comment by JesielPalacios** [comment] 2021-02-26 17:21
@thaJeztah  Mm.. i think that's weird, cause i'm working like administrator user and just trying to deploy an Angular App using the Multi-Stage Build feature from Docker.
I gonna need to get mor info on the internet about how to do it. If you got some info about it i'll be so gratefull to know it. Thanks!

**Comment by almontasser** [comment] 2021-03-02 21:30
If you're working on wsl2 environment this worked for me: `wsl --shutdown`

**Comment by KAVA-Leigh** [comment] 2021-03-10 01:15
> For anyone stumbling across this issue on mac...
> `failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = failed to parse /Users/myusername/.docker/.token_seed: unexpected end of JSON input`
> 
> I just deleted `.token_seed` and `.token_seed.lock` inside of `/Users/myusename/.docker`

@mariusdkm  life saver! thank you.

**Comment by andrew-chang-dewitt** [comment] 2021-03-17 14:52
> 
> 
> @tonistiigi file name is not the only issue here, or I have just another bug
> 
> Here is what I face when running `docker build` command:
> 
> ```shell
> failed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: rpc error: code = Unknown desc = error getting credentials - err: exec: "docker-credential-desktop.exe": executable file not found in $PATH, out: ``
> ```
> 
> Renaming `"credsStore": "desktop.exe"` to `"credStore": "desktop.exe"` in `~/.docker/config.json` is what helped me actually, but it seems like Docker Destkop keeps adding `credsStore` entry in that config file

This was my issue as well. Running Docker Desktop on WSL2. I just changed `credsStore` to `credStore`, so I haven't seen yet if it gets changed back, but I'll update here if it happens to me too. Seems like #444 didn't fix this issue entirely since `credsStore` vs `credStore` wasn't addressed in that PR.

- Docker version 20.10.5, build 55c4c88
- Windows 10 Pro Insider Preview, Build 21332.rs_prerelelease.210306-1859

**Comment by th5** [comment] 2021-03-25 15:30
I was having the "failed to solve with frontend dockerfile.v0: failed to create LLB definition: rpc error: code = Unknown desc = error getting credentials" issue under Docker Desktop Windows/WSL2.

Running with sudo worked for me.

**Comment by antoniobarquero** [comment] 2021-03-29 07:28
Estoy siguiendo los pasos para usar Docker y me salta este error al ejecutar el comando :  docker build -t captacion-php ./   

[+] Building 0.3s (2/2) FINISHED
 => [internal] load build definition from Dockerfile                                                                                       0.1s
 => => transferring dockerfile: 32B                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                          0.1s
 => => transferring context: 2B                                                                                                            0.0s
failed to solve with frontend dockerfile.v0: failed to create LLB definition: dockerfile parse error line 4: unknown instruction: LIBMCRYPT-DEV

¿me echáis una mano? gracias!

**Comment by 0123hoang** [comment] 2021-03-30 04:21
If i run docker build with build kit (DOCKER_BUILDKIT=1 docker build -t base .), the error occurs.
I simply remove that params (docker build -t base .) and its works.

**Comment by subiron** [comment] 2021-04-09 07:35
in my case adding tag after image name resolved the issue.
`FROM nginx`  to  `FROM nginx:latest`

**Comment by abexamir** [comment] 2021-04-29 21:57
There's a problem with your Dockerfile; maybe some of the Dockerfile-specific lines contain illegal words. for example, you may have a line like this:
EXPOSE 3000 # lorem Ipsum blah blah 
that part after # is not treated as a comment, and it ruins the Dockerfile syntax.

**Comment by zsjohny** [comment] 2021-04-30 09:42
Please note at which build stage the error was reported

**Comment by ATpoint** [comment] 2021-05-04 10:09
For me none of the above helped, but to repeat the `docker login` process did the trick.

**Comment by thaJeztah** [comment] 2021-05-04 11:57
I am locking the conversation on this ticket, because it's collecting many comments that are unrelated to the original issue, but let me describe some steps that may help users arriving here.

### Reading the errors produced during build

The error messages returned by current versions of Docker when using BuildKit can be rather verbose, and many will start with the same prefix (`failed to solve.. `). The errors that are printed are a colon (`:`) separated chain of errors from BuildKit's subsystems that are involved in processing the build. The exact errors may differ slightly between versions of Docker, and depending on what "subsystem" the error occurs in, but generally follow the same pattern.

If you get such an error, be sure to read the _whole_ error message; the underlying error is usually at the end. Some examples from the discussion above;

### Example 1

```
failed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: rpc error: code = Unknown desc = error getting credentials - err: exec: "docker-credential-desktop.exe": executable file not found in $PATH, out: ``
```

The above error can be split to:

```
(1) failed to solve with frontend dockerfile.v0:
(2) failed to build LLB: failed to load cache key:
(3) rpc error: code = Unknown desc = error getting credentials - err:
(4) exec: "docker-credential-desktop.exe": executable file not found in $PATH, out: ``
```

Where `(4)` is the underlying error that caused the problem (in this case the client is configured to use the `docker-credential-desktop.exe` credentials-helper, which is not accessible from the WSL2 environment (https://github.com/docker/buildx/issues/415#issuecomment-761857828). `(1) .. (3)` are the BuildKit components that are affected by the underlying problem (the gRPC API, the code constructing the [BuildKit "LLB" graph](https://github.com/moby/buildkit/blob/v0.8.3/README.md#exploring-llb), and the Dockerfile frontend / parser.


### Example 2


```
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to build LLB: Error processing tar file(exit status 1): unexpected EOF
```

```
(1) failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0:
(2) failed to build LLB:
(3) Error processing tar file(exit status 1): unexpected EOF
```

Here, the underlying error is `(3)`, and happened when handling a tar file (without further context / details it's hard to tell what the cause ise, but could be (for example) when using `ADD` to add a remove tar-archive, and there was a networking issue, the server had an issue, or the file that's added is not in the right format).


### Example 3


```
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount840562661/dockerfile: no such file or directory
```

```
(1) failed to solve with frontend dockerfile.v0:
(2) failed to read dockerfile:
(3) open /var/lib/docker/tmp/buildkit-mount840562661/dockerfile:
(4) no such file or directory
```

Here, `(2)...(4)` describe that docker / BuildKit was unable to load the Dockerfile. This looks like the issue that was originally reported, and was related to situations where the Dockerfile was named `dockerfile` (lowercase); fixes for this were merged (https://github.com/docker/buildx/issues/415#issuecomment-730657657).

### Example 4

```
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to solve with frontend gateway.v0: rpc error: code = Unknown desc = failed to build LLB: failed to compute cache key: "/Build/release/authenticator/conf/nginx.conf" not found: not found
```

```
(1) failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0:
(2) failed to solve with frontend gateway.v0:
(3) rpc error: code = Unknown desc = failed to build LLB:
(4) failed to compute cache key: "/Build/release/authenticator/conf/nginx.conf" not found:
(5) not found
```

The `not found` is a bit duplicate here (see https://github.com/moby/buildkit/pull/2047), but the underlying error is that the `nginx.conf` file is not present on your client, is excluded by `.dockerignore`, or (depending on your setup) could be referenced using the wrong "casing" (uppercase/lowercase); double check that the file exists, that it's not excluded by a `.dockerignore` file, that it's readable by the current user, and if the path is correct and has the correct casing.

### Example 5

```
failed to solve with frontend dockerfile.v0: failed to build LLB: error from sender: open node_modules\eslint-plugin-testing-library\node_modules\@typescript-eslint\experimental-utils\_ts3.4\dist\ts-eslint-scope: Access is denied
```

```
(1) failed to solve with frontend dockerfile.v0:
(2) failed to build LLB:
(3) error from sender:
(4) open node_modules\eslint-plugin-testing-library\node_modules\@typescript-eslint\experimental-utils\_ts3.4\dist\ts-eslint-scope:
(5) Access is denied
```

Here the error looks to be on the "client" (cli) side: the docker / buildkit daemon requested the CLI to send a file, but the user running the client did not have access to the file or directory.

Note that filesystem errors (e.g. "Access is denied") may differ between operating systems, and the error message can sometimes be somewhat misleading; they should give you a starting point to debug (and hopefully solve) what's wrong in your situation though.

### Example 6

```
failed to solve with frontend dockerfile.v0: failed to create LLB definition: dockerfile parse error line 4: unknown instruction: LIBMCRYPT-DEV
```

```
(1) failed to solve with frontend dockerfile.v0:
(2) failed to create LLB definition:
(3) dockerfile parse error line 4:
(4) unknown instruction: LIBMCRYPT-DEV
```

This error is a syntax error in the Dockerfile; make sure you didn't miss (for example) a line-continuation (`\`) marker; I expect `LIBMCRYPT-DEV` was part of a `RUN ...` line, but due to a missing line-continuation marker, the Dockerfile parser attempted to read it as a Dockerfile instruction, instead of as part of the `RUN` instruction.

## But these errors are so hard to read!

Yes, some of these errors are horrible; they're often too verbose and while the extra information may help us to find in what part / subsystem of the build process the error is occurring, they can be daunting for users.

We're looking at improving these errors to make the more readable. For example: https://github.com/moby/moby/pull/42329#issuecomment-829039290 shows an improved error message when using Buildx;

```
Dockerfile:3
--------------------
   1 |     # syntax=docker/dockerfile-upstream:master
   2 |     FROM busybox
   3 | >>> RUNCMD
   4 |
--------------------
error: failed to solve: rpc error: code = Unknown desc = failed to create LLB definition: dockerfile parse error line 3: unknown instruction: RUNCMD
```

But further improvements will still be made.

I hope the above helps users that run into errors to narrow down the cause. If you run into an issue, and still think there's a bug, feel free to open a new ticket, but (as may be clear from the above) make sure to include details about the issue, and provide the _exact steps_ to reproduce (taking into account that maintainers of this project do not have access to your private GitHub and Docker Hub repositories).
