### ISSUE TITLE
Multiarch build on multiple nodes does not push to private registry

### ISSUE THREAD

**Issue by MaitreDede** [docker/buildx#478] opened 2020-12-16 00:15 UTC
Hello,

I have a use case of buildx for multi-arch builds, that fails to push to a private registry.

The target goal : a gitlab ci job that will build multi-arch docker images and push to a private insecure registry (for dev builds).
Gitlab jobs runs on kubernetes pods.

I am targetting :
- amd64 : docker daemon `dind` (kubernetes pod on amd64 node)
- arm/v7 : docker daemon on raspberry pi (bare metal)
- arm64/v8 : docker daemon on raspberry pi (bare metal)

When I try to build, I first create `docker context` that targets all three docker instances : `docker context create context-arch --docker="host=tcp://machine:2375/"`

Then, I followed [the doc](https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images) to build multi plateform images. I have added a [config](https://github.com/moby/buildkit/blob/master/docs/buildkitd.toml.md) file to tell my registry is insecure :

```toml
insecure-entitlements = [ "security.insecure" ]

[registry."dkr.isi"]
  http = true
  insecure = true
```
command looks like `docker buildx create --config=config.toml [--use|--append] --name=mybuilder context-arch`.

I build my image with `docker buildx build --tag=privateregistry.local/image/name:random --platform linux/amd64,linux/arm/v7,linux/arm64 --builder=mybuilder --allow security.insecure --push`

The image seams to build correctly, the problem is when it tries to push the image :
```
error: failed to solve: rpc error: code = Unknown desc = failed to copy: failed to do request: Put http://privateregistry.local/v2/image/name/blobs/uploads/4048e098-4e73-40e9-9e45-2d861a4f2d4f?_state=mrs6CVD9vm8FpPOphSc8wFetVPQIAfqHW5lPnIk6tv97Ik5hbWUiOiJkZGFseS9wb2MtYnVpbGR4IiwiVVVJRCI6IjQwNDhlMDk4LTRlNzMtNDBlOS05ZTQ1LTJkODYxYTRmMmQ0ZiIsIk9mZnNldCI6MCwiU3RhcnRlZEF0IjoiMjAyMC0xMi0xNVQyMzoyMDowNS4xOTc1NjYwMDZaIn0%3D&digest=sha256%3Af70c74f2e22556cebd0cbbff78c03d4f0560d76979bf799d67730340a639aa57: readfrom tcp 172.17.0.3:32872->10.107.210.65:80: write tcp 172.17.0.3:32872->10.107.210.65:80: write: connection timed out
```

All docker (servers and cli) are version 20.10.1.
buildx version is `github.com/docker/buildx v0.5.1 11057da37336192bfc57d81e02359ba7ba848e4a`
buildkit docker image is `moby/buildkit:v0.8.1`

Registry is a kubernetes container : `registry:2.7.1` configured as http only.

I can see some activity in registry logs about image : `HEAD /v2/.../blobs/sha256:...` `POST /v2/.../blobs/uploads/` then nothing more but timeout.

**Comment by tonistiigi** [comment] 2020-12-16 20:02
Duplicate of #354

Note that private registries should work fine. Insecure custom config is what is causing the issue.

**Closed by tonistiigi** 2020-12-16 20:02 UTC

**Comment by georgecodes** [comment] 2023-01-22 15:56
@ maitredede After having much a similar problem and getting nowhere for a while, I found a simple 'docker network prune' solved it.  You can possibly rule out buildx by spinning up a bare alpine container and seeing if you can hit your private registry with wget or curl. If not, the issue likely isn't buildx.
