### ISSUE TITLE
Bogus warning from bake using compose file: "ignoring IP-address (127.0.0.1..."

### ISSUE THREAD

**Issue by inickles-grapl** [docker/buildx#552] opened 2021-02-26 15:11 UTC
I'm seeing what looks to me like a bogus warning when running `bake` on a compose file that binds a service port to a specific host interface.

Example:

```
$ docker --version
Docker version 20.10.3, build 48d30b5
$ ls
docker-compose.yml  Dockerfile
$ cat Dockerfile
FROM debian
$ cat docker-compose.yml
version: "3.8"

services:
  bake-compose-wports-test:
    image: bake-compose-wports-test
    build:
      context: .
    ports:
      - "127.0.0.1:1234:1234"
$ docker buildx bake
$ WARN[0000] ignoring IP-address (127.0.0.1:1234:1234/tcp) service will listen on '0.0.0.0' 
...
```

A quick look around the web suggests this is relevant to running Docker Compose in swarm mode, but swarm mode and `ports` aren't relevant here.

**Comment by tonistiigi** [comment] 2021-02-26 19:20
@thaJeztah https://github.com/docker/cli/commit/363335ec9b325ba28e6304fa48c17ab78e4c2a81 . For this context main thing is that just parsing a file should avoid printing to stderr inside the library.

**Comment by tonistiigi** [comment] 2021-03-11 04:10
@thaJeztah Assigned to you but lmk if you think this is by design and should show warning even in here.

**Comment by crazy-max** [comment] 2022-06-10 08:49
Can't repro anymore:

```
$ docker buildx bake --print
{
  "group": {
    "default": {
      "targets": [
        "bake-compose-wports-test"
      ]
    }
  },
  "target": {
    "bake-compose-wports-test": {
      "context": ".",
      "dockerfile": "Dockerfile",
      "tags": [
        "bake-compose-wports-test"
      ]
    }
  }
}
```

**Closed by crazy-max** 2022-06-10 08:49 UTC
