### ISSUE TITLE
unix:///var/run/docker.sock invalid driver option env.http_proxy for docker-container driver

### ISSUE THREAD

**Issue by spejic88** [docker/buildx#212] opened 2019-12-17 10:57 UTC
On the pull request #170 , the option for adding environment variables to docker-container driver were introduced, ex: 
`docker buildx create --driver-opt env.http_proxy=$http_proxy --driver-opt env.https_proxy=$https_proxy --driver-opt '"env.no_proxy='$no_proxy'"'`

However when I run this command I get 
`bold_mcclintock       docker-container                   
  bold_mcclintock0    unix:///var/run/docker.sock invalid driver option env.http_proxy for docker-container driver
`

docker --version
Docker version 19.03.5, build 633a0ea838

docker buildx version
github.com/docker/buildx v0.3.1-tp-docker 6db68d029599c6710a32aa7adcba8e5a344795a7

**Comment by tonistiigi** [comment] 2020-01-14 21:37
@sirlatrom

**Comment by sirlatrom** [comment] 2020-01-15 11:20
I cannot reproduce the message. Maybe it depends on the values of the respective environment variables?

**Comment by ViceIce** [comment] 2020-02-11 18:27
Seeing this too under docker for windows
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by haraldatbmw** [comment] 2020-02-12 08:05
I have the same problems creating a builder with proxy env-variables using the latest Docker Desktop CE for Windows.

```
C:\>docker buildx create --name testbuilder --driver-opt env.http_proxy=host.docker.internal:3128 --driver-opt env.https_proxy=host.docker.internal:3128
testbuilder

C:\>docker buildx use testbuilder

C:\>docker buildx inspect --bootstrap
Name:   testbuilder
Driver: docker-container

Nodes:
Name:     testbuilder0
Endpoint: npipe:////./pipe/docker_engine
Error:    invalid driver option env.http_proxy for docker-container driver
```

```
c:\> docker buildx version
github.com/docker/buildx v0.3.1-tp-docker 6db68d029599c6710a32aa7adcba8e5a344795a7
```

```
c:\> docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by franckOL** [comment] 2020-03-05 07:29
Same issue on ubuntu.

**Comment by jzhengdj** [comment] 2020-03-13 05:19
For me on docker desktop on windows, I won't see the message when I run the commands. However, both `docker buildx ls` and 'docker buildx rm xxxx' will show the error message.

**Comment by jzhengdj** [comment] 2020-03-17 00:17
6db68d0 is behind the merge of #170, need to build from source then the error will be gone.

**Comment by crazy-max** [comment] 2021-06-28 14:26
Fixed by https://github.com/docker/buildx/pull/170

**Closed by crazy-max** 2021-06-28 14:26 UTC
