### ISSUE TITLE
Suggestion: set requirement target for a target (build before)

### ISSUE THREAD

**Issue by back-2-95** [docker/buildx#666] opened 2021-07-07 07:36 UTC
Just basically saying that please build some target before building this target.

Target is using build image from another target in FROM statement.

Example (I used the word require here):

```
target "base-7.3" {
  inherits = ["common", "base"]
  args = {
    PHP_VERSION = "7.3"
    PHP_SHORT_VERSION = "73"
  }
  tags = ["${REPO_BASE}:7.3", "${REPO_BASE}:${PHP73_MINOR}"]
}

target "web-7.3" {
  require = ["base-7.3"]
  inherits = ["common", "base-7.3", "web"]
  tags = ["${REPO_WEB}:7.3", "${REPO_WEB}:${PHP73_MINOR}"]
}
```

**Comment by tonistiigi** [comment] 2021-07-12 02:06
duplicate of #447

**Closed by tonistiigi** 2021-07-12 02:06 UTC
